import { useState } from 'react';
import { Bot, Check, X, RefreshCw, Edit3, Clock, Zap, AlertCircle } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { approveAIDraft, rejectAIDraft, updateAIDraft } from '../../services/aiDrafts';
import type { AIDraft, MessageChannel } from '../../types';

interface AIDraftCardProps {
  draft: AIDraft;
  onApprove: (draft: AIDraft) => void;
  onReject: () => void;
  onRegenerate?: () => void;
  hasNewMessages?: boolean;
}

export function AIDraftCard({
  draft,
  onApprove,
  onReject,
  onRegenerate,
  hasNewMessages,
}: AIDraftCardProps) {
  const { user } = useAuth();
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState(draft.draft_content);
  const [editSubject, setEditSubject] = useState(draft.draft_subject || '');
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [rejectReason, setRejectReason] = useState('');
  const [loading, setLoading] = useState(false);

  const handleApprove = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const approved = await approveAIDraft(draft.id, user.id);
      onApprove(approved);
    } catch (error) {
      console.error('Failed to approve draft:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSaveAndApprove = async () => {
    if (!user) return;
    setLoading(true);
    try {
      await updateAIDraft(draft.id, {
        draft_content: editContent,
        draft_subject: draft.draft_channel === 'email' ? editSubject : undefined,
      });
      const approved = await approveAIDraft(draft.id, user.id);
      onApprove(approved);
    } catch (error) {
      console.error('Failed to save and approve draft:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleReject = async () => {
    setLoading(true);
    try {
      await rejectAIDraft(draft.id, rejectReason || undefined);
      setShowRejectModal(false);
      onReject();
    } catch (error) {
      console.error('Failed to reject draft:', error);
    } finally {
      setLoading(false);
    }
  };

  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="my-4 mx-4">
      <div className="p-4 rounded-lg bg-blue-500/10 border border-blue-500/30">
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-blue-500/20 rounded-lg">
              <Bot size={16} className="text-blue-400" />
            </div>
            <span className="text-sm font-medium text-blue-400">AI Draft</span>
            <span className="px-2 py-0.5 text-xs bg-amber-500/10 text-amber-400 rounded-full">
              Pending Approval
            </span>
          </div>
          <span className="text-xs text-slate-500">{formatTime(draft.created_at)}</span>
        </div>

        {draft.triggered_by_rule && (
          <div className="flex items-center gap-1.5 mb-3 text-xs text-slate-400">
            <Zap size={12} />
            <span>Generated by rule: {draft.triggered_by_rule.name}</span>
          </div>
        )}

        {hasNewMessages && (
          <div className="flex items-center gap-2 mb-3 p-2 bg-amber-500/10 border border-amber-500/30 rounded-lg">
            <AlertCircle size={14} className="text-amber-400" />
            <span className="text-xs text-amber-400">
              Conversation updated - consider regenerating for latest context
            </span>
          </div>
        )}

        {isEditing ? (
          <div className="space-y-3">
            {draft.draft_channel === 'email' && (
              <input
                type="text"
                value={editSubject}
                onChange={(e) => setEditSubject(e.target.value)}
                placeholder="Subject..."
                className="w-full px-3 py-2 bg-slate-900 border border-slate-600 rounded-lg text-white placeholder-slate-500 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            )}
            <textarea
              value={editContent}
              onChange={(e) => setEditContent(e.target.value)}
              rows={5}
              className="w-full px-3 py-2 bg-slate-900 border border-slate-600 rounded-lg text-white placeholder-slate-500 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => {
                  setEditContent(draft.draft_content);
                  setEditSubject(draft.draft_subject || '');
                  setIsEditing(false);
                }}
                className="px-3 py-1.5 text-sm text-slate-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveAndApprove}
                disabled={loading}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-green-600 text-white rounded-lg hover:bg-green-500 disabled:opacity-50 transition-colors"
              >
                <Check size={14} />
                Save & Send
              </button>
            </div>
          </div>
        ) : (
          <>
            {draft.draft_channel === 'email' && draft.draft_subject && (
              <div className="mb-2">
                <span className="text-xs text-slate-500">Subject: </span>
                <span className="text-sm text-white">{draft.draft_subject}</span>
              </div>
            )}
            <div className="p-3 bg-slate-900/50 rounded-lg mb-3">
              <p className="text-sm text-slate-200 whitespace-pre-wrap">{draft.draft_content}</p>
            </div>

            <div className="flex items-center gap-2 text-xs text-slate-500 mb-3">
              <Clock size={12} />
              <span>
                Version {draft.version}
                {draft.context_message_id && ' - Based on conversation at time of generation'}
              </span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleApprove}
                disabled={loading}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-gradient-to-r from-green-500 to-emerald-600 text-white rounded-lg hover:from-green-600 hover:to-emerald-700 disabled:opacity-50 transition-colors"
              >
                <Check size={14} />
                Approve & Send
              </button>
              <button
                onClick={() => setIsEditing(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm border border-slate-600 text-slate-300 rounded-lg hover:bg-slate-700 transition-colors"
              >
                <Edit3 size={14} />
                Edit
              </button>
              <button
                onClick={() => setShowRejectModal(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-red-400 hover:text-red-300 transition-colors"
              >
                <X size={14} />
                Reject
              </button>
              {onRegenerate && (
                <button
                  onClick={onRegenerate}
                  disabled={loading}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-blue-400 hover:text-blue-300 transition-colors ml-auto"
                >
                  <RefreshCw size={14} />
                  Regenerate
                </button>
              )}
            </div>
          </>
        )}
      </div>

      {showRejectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => setShowRejectModal(false)}
          />
          <div className="relative bg-slate-800 rounded-lg shadow-xl w-full max-w-md mx-4 p-6">
            <h3 className="text-lg font-semibold text-white mb-4">Reject Draft</h3>
            <p className="text-sm text-slate-400 mb-4">
              Optionally provide a reason for rejecting this draft. This helps improve future suggestions.
            </p>
            <textarea
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="Reason (optional)..."
              rows={3}
              className="w-full px-3 py-2 bg-slate-900 border border-slate-600 rounded-lg text-white placeholder-slate-500 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-cyan-500 mb-4"
            />
            <div className="flex justify-end gap-3">
              <button
                onClick={() => setShowRejectModal(false)}
                className="px-4 py-2 text-slate-300 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleReject}
                disabled={loading}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-500 disabled:opacity-50 transition-colors"
              >
                {loading ? 'Rejecting...' : 'Reject Draft'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
