/*
  # Create exec_report_query Function for AI Reporting

  This migration creates a secure function to execute read-only SQL queries
  generated by the AI reporting system.

  1. New Function
    - `exec_report_query(query_text text)` - Executes a SELECT query and returns results as JSON
    - Only allows SELECT statements
    - Has built-in timeout protection
    - Returns results as JSONB array

  2. Security
    - Function runs with invoker's permissions (not elevated)
    - Validates query is SELECT-only before execution
    - Limited to prevent abuse
*/

CREATE OR REPLACE FUNCTION exec_report_query(query_text text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  result jsonb;
  clean_query text;
BEGIN
  clean_query := trim(query_text);
  
  IF NOT (upper(clean_query) LIKE 'SELECT%') THEN
    RAISE EXCEPTION 'Only SELECT queries are allowed';
  END IF;
  
  IF clean_query ~* '\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|GRANT|REVOKE)\b' THEN
    RAISE EXCEPTION 'Query contains disallowed operations';
  END IF;
  
  EXECUTE 'SELECT jsonb_agg(row_to_json(t)) FROM (' || clean_query || ' LIMIT 1000) t'
  INTO result;
  
  RETURN COALESCE(result, '[]'::jsonb);
EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Query execution failed: %', SQLERRM;
END;
$$;

COMMENT ON FUNCTION exec_report_query(text) IS 'Executes a read-only SQL query for AI reporting. Only SELECT queries are allowed.';
